import { stringify as yamlStringify } from 'yaml';
import type {
  ConformanceModel,
  CriterionStatus,
  EaaConfig,
  RenderedArtifact,
} from '../types.js';
import { resolveStrings } from '../i18n/strings.js';
import { htmlPage } from './html.js';
import { escapeHtml } from './template.js';
import { sortKeysDeep, stableJson } from '../util/stable.js';

/**
 * ACR / VPAT 2.5 output (FR-ART-2). OpenACR is the interchange format;
 * the HTML and Markdown renditions are views over the OpenACR object.
 */

const ADHERENCE: Record<CriterionStatus, string> = {
  pass: 'supports',
  fail: 'does-not-support',
  partial: 'partially-supports',
  'not-applicable': 'not-applicable',
  'not-evaluated': 'not-evaluated',
};

interface OpenAcrCriterion {
  num: string;
  components: Array<{
    name: string;
    adherence: { level: string; notes: string };
  }>;
}

/** Build the OpenACR document object (deterministic key order applied at serialization). */
export function buildOpenAcr(conformance: ConformanceModel, config: EaaConfig) {
  const byLevel = (level: 'A' | 'AA'): OpenAcrCriterion[] =>
    conformance.results
      .filter((r) => r.criterion.level === level)
      .map((r) => ({
        num: r.criterion.id,
        components: [
          {
            name: 'web',
            adherence: {
              level: ADHERENCE[r.status],
              notes: acrNotes(r.status, r.trace.length, r.clause),
            },
          },
        ],
      }));

  // Field names and structure follow the GSA OpenACR schema so the output
  // is consumable by the OpenACR editor and other ACR tooling.
  return {
    title: `${config.product.name} Accessibility Conformance Report`,
    product: {
      name: config.product.name,
      version: '',
      description: config.product.scope ?? '',
    },
    author: {
      name: config.organisation.name,
      company_name: config.organisation.name,
      email: config.organisation.email ?? '',
      address: config.organisation.address ?? '',
      phone: config.organisation.phone ?? '',
      website: config.organisation.website ?? '',
    },
    vendor: {
      name: config.organisation.name,
      company_name: config.organisation.name,
      email: config.feedback?.email ?? config.organisation.email ?? '',
      address: config.organisation.address ?? '',
      phone: config.feedback?.phone ?? config.organisation.phone ?? '',
      website: config.feedback?.url ?? config.organisation.website ?? '',
    },
    report_date: config.dates.preparation,
    last_modified_date: config.dates.lastReview ?? config.dates.preparation,
    version: 1,
    notes:
      'Generated by eaa-kit from recorded accessibility test evidence. ' +
      'Draft for human review; does not constitute legal advice.',
    evaluation_methods_used:
      config.evaluationMethod ?? 'Automated testing plus manual checklist (see trace artifact).',
    legal_disclaimer:
      'This report is a draft generated from recorded test evidence and must be reviewed by a ' +
      'responsible person before publication. It does not constitute legal advice.',
    repository: '',
    feedback: config.feedback?.url ?? config.feedback?.email ?? config.organisation.email ?? '',
    license: '',
    related_openacr: [],
    catalog: `en-301-549-${conformance.enVersion}-wcag-${conformance.wcagVersion}`,
    chapters: {
      success_criteria_level_a: { notes: '', criteria: byLevel('A') },
      success_criteria_level_aa: { notes: '', criteria: byLevel('AA') },
    },
  };
}

function acrNotes(status: CriterionStatus, evidenceCount: number, clause?: string): string {
  const clausePart = clause ? `EN 301 549 clause ${clause}. ` : '';
  if (status === 'not-evaluated') return `${clausePart}Not yet evaluated.`;
  return `${clausePart}Based on ${evidenceCount} recorded evidence entr${evidenceCount === 1 ? 'y' : 'ies'}; see the trace artifact for criterion-level provenance.`;
}

export interface AcrRenderOptions {
  format: 'openacr' | 'yaml' | 'json' | 'html' | 'md';
  lang?: string;
  reviewedBy?: string;
  reviewedOn?: string;
}

export function renderAcr(
  conformance: ConformanceModel,
  config: EaaConfig,
  opts: AcrRenderOptions
): RenderedArtifact {
  const doc = buildOpenAcr(conformance, config);
  const lang = opts.lang ?? 'en';
  const t = resolveStrings(lang);
  const reviewed = Boolean(
    (opts.reviewedBy ?? config.review?.reviewedBy) && (opts.reviewedOn ?? config.review?.reviewedOn)
  );

  if (opts.format === 'openacr' || opts.format === 'yaml') {
    return {
      kind: 'acr',
      format: 'openacr',
      lang,
      filenameHint: 'acr.openacr.yaml',
      content: yamlStringify(sortKeysDeep(doc)),
    };
  }
  if (opts.format === 'json') {
    return {
      kind: 'acr',
      format: 'json',
      lang,
      filenameHint: 'acr.openacr.json',
      content: stableJson(doc),
    };
  }

  const s = (path: string): string => {
    let cur: unknown = t;
    for (const p of path.split('.')) cur = (cur as Record<string, unknown> | undefined)?.[p];
    return typeof cur === 'string' ? cur : path;
  };

  const chapterRows = (level: 'A' | 'AA') =>
    conformance.results
      .filter((r) => r.criterion.level === level)
      .map((r) => ({
        num: r.criterion.id,
        name: r.criterion.name,
        clause: r.clause ?? '—',
        level: ADHERENCE[r.status],
        label: s(`common.status.${r.status}`),
        fail: r.status === 'fail' || r.status === 'partial',
      }));

  if (opts.format === 'md') {
    const lines: string[] = [];
    if (!reviewed) lines.push(`> **${s('common.draftWatermark')}**`, '');
    lines.push(`# ${doc.title}`, '');
    lines.push(`${s('acr.basedOn')}. ${escapeNothing(doc.notes)}`, '');
    lines.push(`## ${s('acr.productHeading')}`, '');
    lines.push(`- **${s('acr.productHeading')}:** ${doc.product.name}`);
    lines.push(`- **Author:** ${doc.author.name}`);
    lines.push(`- **Report date:** ${doc.report_date}`);
    lines.push(`- **Catalog:** ${doc.catalog}`, '');
    for (const [heading, level] of [
      [s('acr.chapterA'), 'A'],
      [s('acr.chapterAA'), 'AA'],
    ] as const) {
      lines.push(`## ${heading}`, '');
      lines.push(`| ${s('acr.criterionHeading')} | EN 301 549 | ${s('acr.levelHeading')} | ${s('acr.remarksHeading')} |`);
      lines.push('| --- | --- | --- | --- |');
      for (const row of chapterRows(level)) {
        lines.push(`| ${row.num} ${row.name} | ${row.clause} | ${row.level} | ${row.label} |`);
      }
      lines.push('');
    }
    return {
      kind: 'acr',
      format: 'md',
      lang,
      filenameHint: 'acr.md',
      content: lines.join('\n'),
    };
  }

  const table = (caption: string, level: 'A' | 'AA') => {
    const rows = chapterRows(level)
      .map(
        (r) =>
          `<tr><th scope="row">${escapeHtml(`${r.num} ${r.name}`)}</th>` +
          `<td>${escapeHtml(r.clause)}</td>` +
          `<td class="${r.fail ? 'status-fail' : 'status-pass'}">${escapeHtml(r.level)}</td>` +
          `<td>${escapeHtml(r.label)}</td></tr>`
      )
      .join('\n');
    return `<table>
<caption>${escapeHtml(caption)}</caption>
<thead><tr><th scope="col">${escapeHtml(s('acr.criterionHeading'))}</th><th scope="col">EN 301 549</th><th scope="col">${escapeHtml(s('acr.levelHeading'))}</th><th scope="col">${escapeHtml(s('acr.remarksHeading'))}</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>`;
  };

  const body = `<h1>${escapeHtml(doc.title)}</h1>
<p class="meta">${escapeHtml(s('acr.basedOn'))} · ${escapeHtml(doc.report_date)}</p>
<h2>${escapeHtml(s('acr.productHeading'))}</h2>
<ul>
<li>${escapeHtml(doc.product.name)}</li>
<li>${escapeHtml(doc.author.name)}</li>
<li>${escapeHtml(doc.catalog)}</li>
</ul>
${table(s('acr.chapterA'), 'A')}
${table(s('acr.chapterAA'), 'AA')}`;

  return {
    kind: 'acr',
    format: 'html',
    lang,
    filenameHint: 'acr.html',
    content: htmlPage(body, {
      lang,
      title: doc.title,
      watermark: reviewed ? undefined : s('common.draftWatermark'),
      reviewedLine: reviewed
        ? `${s('common.reviewedBy')}: ${opts.reviewedBy ?? config.review?.reviewedBy} · ${s('common.reviewedOn')}: ${opts.reviewedOn ?? config.review?.reviewedOn}`
        : undefined,
      footer: s('common.generatedBy'),
    }),
  };
}

function escapeNothing(s: string): string {
  return s;
}
